apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb-smartfarm
    url: db:5432
    database: smartfarm
    user: farm_admin
    secureJsonData:
      password: hackathon_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
      timezone: Europe/Sofia
    editable: true
