apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb-smartfarm
    # On Windows Docker Desktop, host.docker.internal resolves to the host machine
    url: host.docker.internal:5432
    database: smartfarm
    user: farm_admin
    secureJsonData:
      password: hackathon_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    editable: true
